#!/usr/bin/env bash
# displays the list of currently running processes.
# shows all processes, for all users, including those
# which might not have a TTY
# Display in a user-oriented format
# Shows the process hierarchy

ps -auxf
